version: '3.8'  # Specify version
services:
  postgres:
    container_name: ftbsolutions_postgres
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_USER: ftsolutionadmin
      POSTGRES_PASSWORD: ftsolution
      POSTGRES_DB: ftsolution_db
    ports:
      - "5124:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    container_name: ftbsolutions_app
    build:
      context: .
      dockerfile: Dockerfile
    image: ftbsolutions:latest  # Tag for the image
    depends_on:
      - postgres
    dns:
      - 8.8.8.8
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ftsolution_db
      - SPRING_DATASOURCE_USERNAME=ftsolutionadmin
      - SPRING_DATASOURCE_PASSWORD=ftsolution
